apiVersion: v1 
kind: ConfigMap
metadata:
  name: env-config-html
data:
  index.html: |
    <!DOCTYPE html>
    <html lang="en">
    <head>
      <meta charset="UTF-8">
      <title>Пример HTML-документа</title>
    </head>
    <body>
      <h1>Заголовок страницы</h1>
      <p>Это пример простого HTML-документа.</p>
    </body>
    </html>